%%  Experimental log file generated by CLog2 class
%  2009 Alexander Pastukhov (pastukhov.alexander@gmail.com)
%  For uploading into matlab just run it as a script.
%  It will generate an array of structures Block(N), where N is number of blocks
%  Settings for each block are in .Settings substructure
%  Parameters (settings which define different conditions) are in substructure .Parameters
%  Data specific for individual trials is in .Trial(M) substructure, where M is number of trials
Block= [];

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '19-02-2010 14:30:51';
CurrentBlock.Timestamps.BlockStart= '19-02-2010 14:31:00';
CurrentBlock.Timestamps.BlockEnd= '19-02-2010 14:31:34';
CurrentBlock.Parameters.MasksNumber= 3;
CurrentBlock.Settings.MasksNumber= 3;
CurrentBlock.Parameters.KanitzaIsAligned= 1;
CurrentBlock.Settings.KanitzaIsAligned= 1;
CurrentBlock.Parameters.Subject= '13';
CurrentBlock.Settings.Subject= '13';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 30;
CurrentBlock.Settings.TrialDuration_SEC= 30;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1384];
CurrentBlock.Target= [2, 1, 1, 2, 1, 2, 0, 2, 1, 0];
CurrentBlock.Event= [0, 0, 1, 1, 0, 0, 0, 1, 1, 1];
CurrentBlock.Time= [9562, 10178, 10511, 11361, 22224, ...
    22257, 22291, 23640, 23690, 23707];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '19-02-2010 14:30:51';
CurrentBlock.Timestamps.BlockStart= '19-02-2010 14:31:34';
CurrentBlock.Timestamps.BlockEnd= '19-02-2010 14:32:25';
CurrentBlock.Parameters.MasksNumber= 1;
CurrentBlock.Settings.MasksNumber= 1;
CurrentBlock.Parameters.KanitzaIsAligned= 0;
CurrentBlock.Settings.KanitzaIsAligned= 0;
CurrentBlock.Parameters.Subject= '13';
CurrentBlock.Settings.Subject= '13';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 30;
CurrentBlock.Settings.TrialDuration_SEC= 30;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1176];
CurrentBlock.Target= [1, 1, 0, 1, 0, 1, 1, 2, 0, 2, 1, ...
    0, 1, 2, 2, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 2, 0, 0, ...
    2, 1, 1, 0, 2, 2, 0, 1];
CurrentBlock.Event= [0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, ...
    0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, ...
    1, 0, 0, 0, 1, 1, 1];
CurrentBlock.Time= [13055, 13588, 15205, 15321, 15471, ...
    16104, 19002, 19070, 19103, 19552, 19570, 19586, ...
    20319, 20536, 20835, 20918, 20968, 21002, 21036, ...
    21286, 22718, 22785, 22918, 23018, 25284, 25317, ...
    25383, 25867, 25883, 25900, 27283, 27316, 27335, ...
    27500, 27516, 27533];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '19-02-2010 14:30:51';
CurrentBlock.Timestamps.BlockStart= '19-02-2010 14:32:25';
CurrentBlock.Timestamps.BlockEnd= '19-02-2010 14:33:00';
CurrentBlock.Parameters.MasksNumber= 1;
CurrentBlock.Settings.MasksNumber= 1;
CurrentBlock.Parameters.KanitzaIsAligned= 1;
CurrentBlock.Settings.KanitzaIsAligned= 1;
CurrentBlock.Parameters.Subject= '13';
CurrentBlock.Settings.Subject= '13';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 30;
CurrentBlock.Settings.TrialDuration_SEC= 30;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1091];
CurrentBlock.Target= [0, 1, 1, 0];
CurrentBlock.Event= [0, 0, 1, 1];
CurrentBlock.Time= [4398, 4531, 4714, 5547];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '19-02-2010 14:30:51';
CurrentBlock.Timestamps.BlockStart= '19-02-2010 14:33:00';
CurrentBlock.Timestamps.BlockEnd= '19-02-2010 14:33:34';
CurrentBlock.Parameters.MasksNumber= 3;
CurrentBlock.Settings.MasksNumber= 3;
CurrentBlock.Parameters.KanitzaIsAligned= 0;
CurrentBlock.Settings.KanitzaIsAligned= 0;
CurrentBlock.Parameters.Subject= '13';
CurrentBlock.Settings.Subject= '13';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 30;
CurrentBlock.Settings.TrialDuration_SEC= 30;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1383];
CurrentBlock.Target= [2, 1, 0, 2, 1, 0, 0, 1, 2, 2, 1, ...
    0, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 2, 2, 0, 0, 2, 2, ...
    0, 1, 0, 1];
CurrentBlock.Event= [0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, ...
    0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, ...
    0, 1, 1];
CurrentBlock.Time= [8787, 9071, 9337, 9953, 9970, 9987, ...
    13686, 13702, 13736, 14935, 15018, 15034, 16301, ...
    16334, 16751, 16768, 18750, 18883, 20317, 20367, ...
    21766, 21816, 23515, 23682, 25764, 26481, 26947, ...
    27463, 27880, 28230, 28280, 28846];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '19-02-2010 14:30:51';
CurrentBlock.Timestamps.BlockStart= '19-02-2010 14:33:34';
CurrentBlock.Timestamps.BlockEnd= '19-02-2010 14:35:41';
CurrentBlock.Parameters.MasksNumber= 3;
CurrentBlock.Settings.MasksNumber= 3;
CurrentBlock.Parameters.KanitzaIsAligned= 1;
CurrentBlock.Settings.KanitzaIsAligned= 1;
CurrentBlock.Parameters.Subject= '13';
CurrentBlock.Settings.Subject= '13';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 120;
CurrentBlock.Settings.TrialDuration_SEC= 120;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1100];
CurrentBlock.Target= [0, 1, 2, 0, 0, 2, 0, 1, 2, 1, 0, ...
    2, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 2, 2, 1, 0, 0, 1, ...
    2, 2, 1, 0, 0, 1, 1, 0, 2, 2, 1, 1, 0, 0, 0, 2, 1, ...
    2, 0, 1, 1, 1, 1, 2, 0, 1, 2, 0, 1, 0, 2, 2, 0, 1, ...
    1, 0, 1, 0, 1, 2, 0, 2, 1, 0, 1, 2, 0, 2, 1, 0, 1, ...
    0, 2, 2, 1, 0, 1, 0, 2, 0, 2, 1, 1, 1, 1, 1, 0, 0, ...
    1, 2, 0, 0, 2, 1, 1, 2, 0, 0, 2, 1, 1, 0, 2, 2, 0, ...
    1, 0, 1, 2, 2, 1, 0, 1, 2, 0, 2, 1, 0, 1, 0, 0, 1, ...
    1, 2, 0, 2, 1, 0, 1, 2, 0, 2, 1, 0, 1, 0, 2, 2, 1, ...
    0, 2, 1, 2, 2, 0, 0, 1, 1, 2, 1, 1, 0, 2, 2, 0, 1];
CurrentBlock.Event= [0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, ...
    1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, ...
    1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, ...
    1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, ...
    0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, ...
    0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, ...
    0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, ...
    0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, ...
    0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, ...
    0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1];
CurrentBlock.Time= [7795, 7828, 7878, 8011, 8311, 9494, ...
    9594, 9610, 12909, 12942, 13809, 14375, 14392, ...
    14408, 19957, 20023, 20173, 20840, 28653, 28803, ...
    30869, 30886, 30952, 32835, 32886, 32901, 35950, ...
    35985, 36034, 37767, 37850, 37899, 42598, 42831, ...
    43181, 43197, 43481, 43681, 43714, 43914, 44081, ...
    44214, 48062, 48079, 48112, 50229, 50245, 50262, ...
    54011, 54344, 57060, 57143, 57159, 58658, 58792, ...
    59325, 61058, 61124, 61225, 61541, 61607, 61624, ...
    61857, 61874, 61990, 62007, 63724, 63823, 63890, ...
    64223, 64239, 64257, 68405, 68455, 68472, 70388, ...
    70421, 70454, 78034, 78067, 78084, 78900, 79301, ...
    79501, 79967, 80833, 81217, 81267, 81366, 81434, ...
    81916, 82033, 82267, 82316, 82850, 83366, 85498, ...
    85665, 86265, 86698, 87265, 87348, 88863, 88931, ...
    88964, 89597, 89613, 89646, 92312, 92346, 92362, ...
    93262, 93279, 93312, 93879, 93929, 93979, 94645, ...
    94712, 94745, 96378, 96444, 96478, 96860, 96928, ...
    96944, 98677, 98693, 99760, 99776, 102792, 102842, ...
    102858, 103592, 103642, 103675, 105508, 105541, ...
    105574, 106374, 106490, 106523, 107207, 107224, ...
    107340, 108123, 108206, 108223, 111355, 111438, ...
    111472, 111771, 112788, 112888, 113154, 113654, ...
    113671, 113721, 119019, 119052, 119069, 119902, ...
    120000, 120000];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '19-02-2010 14:30:51';
CurrentBlock.Timestamps.BlockStart= '19-02-2010 14:35:41';
CurrentBlock.Timestamps.BlockEnd= '19-02-2010 14:37:46';
CurrentBlock.Parameters.MasksNumber= 1;
CurrentBlock.Settings.MasksNumber= 1;
CurrentBlock.Parameters.KanitzaIsAligned= 0;
CurrentBlock.Settings.KanitzaIsAligned= 0;
CurrentBlock.Parameters.Subject= '13';
CurrentBlock.Settings.Subject= '13';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 120;
CurrentBlock.Settings.TrialDuration_SEC= 120;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1343];
CurrentBlock.Target= [0, 1, 2, 2, 1, 0, 0, 1, 2, 2, 2, ...
    2, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 2, 2, 0, 1, 0, ...
    1, 1, 2, 2, 2, 2, 0, 0, 1, 0, 1, 0, 2, 2, 1, 0, 1, ...
    0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 2, 1, 2, 0, 1, 1, 0, ...
    2, 2, 1, 0, 0, 1, 2, 2, 1, 0, 1, 0, 0, 1, 1, 1, 0, ...
    0, 1, 1, 0, 0, 2, 2, 1, 1, 0, 0, 1, 1, 0, 1, 2, 2, ...
    1, 0, 1, 2, 0, 2, 1, 0, 0, 1, 2, 2, 1, 0, 0, 2, 1, ...
    2, 1, 0, 0, 2, 1, 0, 1, 2, 0, 1, 1, 0, 1, 2, 1, 2, ...
    0, 1, 0, 1, 2, 1, 2, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, ...
    1, 1, 0, 0, 2, 1, 0, 2, 1, 0, 2, 1, 2, 1, 0, 2, 0, ...
    1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 1, 0];
CurrentBlock.Event= [0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, ...
    1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, ...
    1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, ...
    0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, ...
    1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, ...
    0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, ...
    1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, ...
    1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, ...
    0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, ...
    1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, ...
    1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1];
CurrentBlock.Time= [6588, 6604, 6621, 7070, 7103, 7138, ...
    10919, 12652, 12702, 12885, 13002, 13252, 13318, ...
    13335, 14484, 14834, 16117, 16200, 16601, 16684, ...
    16983, 17566, 17784, 18316, 18600, 18800, 18899, ...
    18982, 26613, 26847, 27097, 27229, 28430, 28479, ...
    28546, 28596, 30795, 30911, 31278, 31428, 31944, ...
    32078, 32378, 32577, 32829, 32878, 33544, 33860, ...
    35293, 35443, 35477, 35710, 36626, 36776, 37542, ...
    37559, 37576, 37926, 37942, 37959, 39892, 39925, ...
    39975, 40175, 40241, 40258, 45256, 45323, 45356, ...
    45772, 46006, 46072, 48571, 49121, 49271, 49321, ...
    54036, 54303, 54669, 54786, 55303, 55419, 55603, ...
    55735, 56169, 56352, 56618, 56735, 57085, 57168, ...
    57201, 57219, 59317, 59417, 59451, 59700, 59751, ...
    59784, 64799, 64865, 64882, 65299, 65315, 65332, ...
    67131, 67198, 67231, 68181, 68214, 68581, 69347, ...
    69380, 69396, 69896, 69964, 69980, 70946, 71046, ...
    71063, 71479, 71612, 71663, 76611, 76744, 77044, ...
    77110, 77660, 77693, 77910, 77943, 78227, 78311, ...
    78510, 78544, 78793, 78927, 79026, 79144, 79443, ...
    79526, 79760, 79859, 80159, 80176, 80409, 80426, ...
    83691, 83708, 84158, 84175, 85641, 85690, 85724, ...
    86157, 86457, 86490, 87873, 87990, 88040, 88640, ...
    88656, 88739, 90239, 90256, 90289, 91589, 91788, ...
    92621, 92705, 92738, 97953, 97986, 98003, 98753, ...
    98769, 98819];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '19-02-2010 14:30:51';
CurrentBlock.Timestamps.BlockStart= '19-02-2010 14:37:46';
CurrentBlock.Timestamps.BlockEnd= '19-02-2010 14:41:14';
CurrentBlock.Parameters.MasksNumber= 1;
CurrentBlock.Settings.MasksNumber= 1;
CurrentBlock.Parameters.KanitzaIsAligned= 1;
CurrentBlock.Settings.KanitzaIsAligned= 1;
CurrentBlock.Parameters.Subject= '13';
CurrentBlock.Settings.Subject= '13';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 120;
CurrentBlock.Settings.TrialDuration_SEC= 120;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1333];
CurrentBlock.Target= [1, 0, 2, 2, 2, 1, 2, 0, 1, 0, 2, ...
    2, 1, 0, 1, 1, 1, 2, 2, 1, 1, 1, 0, 0, 0, 0, 1, 1, ...
    1, 1, 1, 0, 2, 2, 1, 0, 2, 1, 1, 1, 0, 0, 1, 2, 1, ...
    0, 0, 1, 0, 2, 1, 1, 2, 0, 1, 0, 2, 2, 1, 0, 2, 0, ...
    1, 2, 1, 0, 1, 0, 1, 0, 2, 2, 1, 0, 2, 2, 1, 0, 1, ...
    1, 2, 1, 0, 2, 1, 0, 1, 2, 2, 1, 1, 1, 0, 0, 1, 0, ...
    1, 0, 2, 2, 0, 2, 1, 0, 2, 1, 1, 2, 1, 2, 1, 2, 2, ...
    1, 0, 1, 1, 0, 1, 2, 2, 1, 1, 2, 1, 2];
CurrentBlock.Event= [0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, ...
    1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, ...
    1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, ...
    1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, ...
    1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, ...
    0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, ...
    1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, ...
    0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1];
CurrentBlock.Time= [20835, 20851, 21001, 21201, 21351, ...
    21451, 21567, 21601, 27065, 27132, 27166, 27799, ...
    27815, 27849, 30281, 30498, 38545, 38761, 39095, ...
    39111, 41427, 41627, 41960, 42343, 42743, 43276, ...
    44226, 44392, 45309, 45842, 46458, 46892, 46941, ...
    47308, 47392, 47541, 48940, 49023, 49141, 49690, ...
    49940, 50273, 50307, 50323, 53322, 53506, 54089, ...
    54105, 56204, 57088, 57171, 57537, 59054, 59120, ...
    62053, 62219, 62419, 62919, 62969, 62985, 66467, ...
    66484, 66551, 71232, 71249, 71266, 72798, 72865, ...
    73798, 73814, 74248, 74730, 75381, 75414, 75514, ...
    75897, 75947, 75980, 77796, 78446, 80245, 80262, ...
    80295, 81328, 81378, 81412, 92024, 92225, 93290, ...
    93324, 95756, 96173, 99854, 100338, 101687, 102054, ...
    102737, 102887, 104086, 104886, 106952, 107002, ...
    107052, 107368, 107901, 107918, 109367, 109434, ...
    110601, 110667, 112649, 112800, 113433, 113466, ...
    115549, 115599, 115731, 117498, 118281, 118647, ...
    119064, 119098, 119880, 120014, 120000, 120000];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '19-02-2010 14:30:51';
CurrentBlock.Timestamps.BlockStart= '19-02-2010 14:41:14';
CurrentBlock.Timestamps.BlockEnd= '19-02-2010 14:43:22';
CurrentBlock.Parameters.MasksNumber= 3;
CurrentBlock.Settings.MasksNumber= 3;
CurrentBlock.Parameters.KanitzaIsAligned= 0;
CurrentBlock.Settings.KanitzaIsAligned= 0;
CurrentBlock.Parameters.Subject= '13';
CurrentBlock.Settings.Subject= '13';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 120;
CurrentBlock.Settings.TrialDuration_SEC= 120;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1363];
CurrentBlock.Target= [2, 2, 1, 2, 0, 1, 2, 0, 1, 1, 2, ...
    1, 0, 0, 2, 1, 1, 2, 2, 1, 1, 2, 0, 2, 1, 0, 1, 2, ...
    2, 1, 0, 0, 2, 2, 0, 0, 0, 2, 1, 1, 0, 2, 0, 2, 1, ...
    2, 0, 1, 0, 1, 2, 2, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, ...
    0, 1, 1, 0, 2, 2, 2, 2, 1, 1, 1, 2, 0, 0, 2, 1, 1, ...
    2, 0, 1, 2, 0, 2, 0, 1, 1, 2, 0, 1, 0, 2, 0, 2, 1, ...
    0, 2, 1, 2, 1, 0, 2, 1, 0, 2, 1, 0, 1, 1];
CurrentBlock.Event= [0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, ...
    0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, ...
    1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, ...
    1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, ...
    0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, ...
    0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, ...
    0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1];
CurrentBlock.Time= [5279, 6328, 15491, 15625, 16058, ...
    16591, 16657, 16674, 21655, 22705, 24855, 24871, ...
    26089, 26370, 26404, 26421, 27954, 29653, 30153, ...
    30252, 32968, 33319, 34117, 34584, 34651, 34851, ...
    36900, 36984, 38033, 38050, 38866, 40082, 40516, ...
    41765, 41781, 42614, 43947, 43964, 43997, 44347, ...
    44363, 44381, 49795, 49862, 49878, 50196, 50728, ...
    50744, 53210, 53227, 53243, 54710, 54760, 54777, ...
    56409, 57276, 58408, 59558, 60374, 60841, 61724, ...
    61740, 62840, 64123, 64473, 64539, 64607, 65089, ...
    66072, 66505, 70620, 71870, 76035, 76185, 76236, ...
    77418, 77768, 77818, 86898, 86914, 87031, 88663, ...
    88714, 88731, 92262, 92329, 92379, 93828, 93929, ...
    93962, 102276, 103574, 104025, 104707, 104824, ...
    104841, 106524, 106557, 106573, 108123, 108206, ...
    108239, 113287, 113771, 116286, 116987, 118220, ...
    118303, 119585, 120000];
Block{length(Block)+1}= CurrentBlock;

