%%  Experimental log file generated by CLog2 class
%  2009 Alexander Pastukhov (pastukhov.alexander@gmail.com)
%  For uploading into matlab just run it as a script.
%  It will generate an array of structures Block(N), where N is number of blocks
%  Settings for each block are in .Settings substructure
%  Parameters (settings which define different conditions) are in substructure .Parameters
%  Data specific for individual trials is in .Trial(M) substructure, where M is number of trials
Block= [];

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '04-03-2010 17:40:48';
CurrentBlock.Timestamps.BlockStart= '04-03-2010 17:40:52';
CurrentBlock.Timestamps.BlockEnd= '04-03-2010 17:41:26';
CurrentBlock.Parameters.MasksNumber= 1;
CurrentBlock.Settings.MasksNumber= 1;
CurrentBlock.Parameters.KanitzaIsAligned= 0;
CurrentBlock.Settings.KanitzaIsAligned= 0;
CurrentBlock.Parameters.Subject= '20';
CurrentBlock.Settings.Subject= '20';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 30;
CurrentBlock.Settings.TrialDuration_SEC= 30;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1198];
CurrentBlock.Target= [2, 2, 1, 1, 0, 2, 1, 2, 1, 0, 1, ...
    1, 1, 2, 0, 2, 1, 0, 1, 2, 0, 2, 1, 0];
CurrentBlock.Event= [0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, ...
    0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1];
CurrentBlock.Time= [5826, 5843, 14123, 15806, 19021, ...
    19188, 19221, 20354, 20387, 20438, 24436, 24519, ...
    26052, 26135, 26185, 27034, 27069, 27085, 28435, ...
    28468, 28534, 29934, 30000, 30000];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '04-03-2010 17:40:48';
CurrentBlock.Timestamps.BlockStart= '04-03-2010 17:41:26';
CurrentBlock.Timestamps.BlockEnd= '04-03-2010 17:42:01';
CurrentBlock.Parameters.MasksNumber= 3;
CurrentBlock.Settings.MasksNumber= 3;
CurrentBlock.Parameters.KanitzaIsAligned= 1;
CurrentBlock.Settings.KanitzaIsAligned= 1;
CurrentBlock.Parameters.Subject= '20';
CurrentBlock.Settings.Subject= '20';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 30;
CurrentBlock.Settings.TrialDuration_SEC= 30;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1469];
CurrentBlock.Target= [1, 1, 0, 0, 2, 2, 1, 0, 1, 0, 1, ...
    0, 2, 2, 1, 0, 2, 2, 1, 0, 1, 0, 2, 2];
CurrentBlock.Event= [0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, ...
    0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1];
CurrentBlock.Time= [15204, 15437, 16953, 17153, 22351, ...
    22500, 22601, 22901, 23084, 23167, 24217, 24267, ...
    24317, 24733, 24767, 24800, 26366, 26499, 27799, ...
    27849, 28082, 28099, 28632, 28798];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '04-03-2010 17:40:48';
CurrentBlock.Timestamps.BlockStart= '04-03-2010 17:42:01';
CurrentBlock.Timestamps.BlockEnd= '04-03-2010 17:42:37';
CurrentBlock.Parameters.MasksNumber= 3;
CurrentBlock.Settings.MasksNumber= 3;
CurrentBlock.Parameters.KanitzaIsAligned= 0;
CurrentBlock.Settings.KanitzaIsAligned= 0;
CurrentBlock.Parameters.Subject= '20';
CurrentBlock.Settings.Subject= '20';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 30;
CurrentBlock.Settings.TrialDuration_SEC= 30;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1466];
CurrentBlock.Target= [1, 2, 2, 1, 0, 1, 2, 2, 1, 0, 2, ...
    1, 0, 2, 1, 0, 1, 2, 0, 2, 1, 0, 1, 1, 1, 2, 0, 2, ...
    1, 0, 1, 2, 0, 2, 1, 0, 1, 1, 2, 1, 2, 1, 2, 2];
CurrentBlock.Event= [0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, ...
    0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, ...
    1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1];
CurrentBlock.Time= [8550, 8649, 8750, 8766, 9199, 9216, ...
    9250, 9482, 9516, 9533, 12132, 12181, 12514, 14215, ...
    14265, 14281, 16363, 16396, 16464, 17880, 17896, ...
    17946, 22494, 22761, 22894, 23095, 23111, 24227, ...
    24310, 24344, 25410, 25460, 25610, 25826, 25844, ...
    25860, 26960, 27243, 27359, 27475, 27692, 27742, ...
    28844, 30000];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '04-03-2010 17:40:48';
CurrentBlock.Timestamps.BlockStart= '04-03-2010 17:42:37';
CurrentBlock.Timestamps.BlockEnd= '04-03-2010 17:43:11';
CurrentBlock.Parameters.MasksNumber= 1;
CurrentBlock.Settings.MasksNumber= 1;
CurrentBlock.Parameters.KanitzaIsAligned= 1;
CurrentBlock.Settings.KanitzaIsAligned= 1;
CurrentBlock.Parameters.Subject= '20';
CurrentBlock.Settings.Subject= '20';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 30;
CurrentBlock.Settings.TrialDuration_SEC= 30;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1186];
CurrentBlock.Target= [0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 2, ...
    2, 1, 0, 2, 1, 0, 2, 1, 0, 1, 2, 0, 2, 1, 0, 1, 2, ...
    0, 2, 1, 0, 1, 0, 2, 2, 1, 0];
CurrentBlock.Event= [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, ...
    1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, ...
    1, 1, 1, 0, 0, 0, 1, 1, 1];
CurrentBlock.Time= [4292, 5608, 5642, 6108, 10756, ...
    11206, 12238, 12306, 13638, 13871, 14188, 14505, ...
    14522, 14555, 18087, 18104, 18586, 19220, 19236, ...
    19253, 21585, 21602, 21735, 22218, 22252, 22269, ...
    24768, 24801, 24967, 25934, 25950, 25983, 27333, ...
    27616, 27649, 28233, 28316, 28350];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '04-03-2010 17:40:48';
CurrentBlock.Timestamps.BlockStart= '04-03-2010 17:43:11';
CurrentBlock.Timestamps.BlockEnd= '04-03-2010 17:46:12';
CurrentBlock.Parameters.MasksNumber= 1;
CurrentBlock.Settings.MasksNumber= 1;
CurrentBlock.Parameters.KanitzaIsAligned= 0;
CurrentBlock.Settings.KanitzaIsAligned= 0;
CurrentBlock.Parameters.Subject= '20';
CurrentBlock.Settings.Subject= '20';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 120;
CurrentBlock.Settings.TrialDuration_SEC= 120;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1020];
CurrentBlock.Target= [0, 0, 2, 1, 2, 0, 1, 0, 1, 1, 0, ...
    0, 0, 0, 2, 2, 1, 0, 2, 2, 0, 1, 1, 0, 2, 2, 1, 0, ...
    1, 0, 1, 2, 2, 1, 0, 1, 2, 2, 0, 0, 2, 0, 2, 0, 0, ...
    0, 0, 2, 1, 2, 0, 1, 1, 1, 0, 1, 0, 1, 1, 2, 2, 1, ...
    1, 2, 0, 2, 0, 1, 1, 2, 0, 2, 1, 0, 1, 1, 1, 0, 1, ...
    1, 0, 1, 2, 1, 0, 2, 1, 0, 1, 2, 0, 2, 0, 1, 2, 2, ...
    1, 0, 2, 2, 1, 0, 2, 1, 2, 2, 2, 1, 2, 0, 2, 0, 0, ...
    1, 2, 0, 1, 2, 0, 2, 1, 2, 1, 0, 1, 2, 0, 2, 1, 0, ...
    1, 0, 2, 2, 1, 0, 1, 2, 0, 2, 1, 0, 1, 2, 0, 2, 1, ...
    0, 1, 1, 2, 0, 2, 0, 2, 0, 1, 2, 1, 0, 0, 2, 1, 2, ...
    1, 0, 1, 0, 2, 2, 1, 0, 1, 2, 1, 2, 1, 1, 2, 1, 0, ...
    1, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 1, 2, 1, 0, 1, 2, ...
    0, 2, 1, 0];
CurrentBlock.Event= [0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, ...
    0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, ...
    0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, ...
    0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, ...
    0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, ...
    1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, ...
    0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, ...
    0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, ...
    0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, ...
    0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, ...
    1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, ...
    1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, ...
    1, 1, 1];
CurrentBlock.Time= [4202, 4452, 4486, 4686, 4719, 4936, ...
    5019, 5069, 7284, 7518, 7685, 7918, 8768, 8985, ...
    9101, 10367, 11067, 11300, 11383, 11866, 11883, ...
    11900, 14782, 14899, 14965, 16765, 16815, 16831, ...
    29743, 30426, 30492, 31658, 31726, 31759, 32009, ...
    32158, 32192, 32226, 32276, 32325, 32425, 32725, ...
    33925, 33942, 37573, 37840, 38423, 38623, 38739, ...
    39606, 39639, 39655, 44271, 44471, 44688, 44721, ...
    46003, 46020, 46220, 46420, 47103, 47136, 48020, ...
    48287, 48419, 48785, 48819, 48836, 49785, 49902, ...
    49918, 52218, 52268, 52301, 52584, 52634, 52667, ...
    52735, 52818, 52950, 53851, 53867, 53917, 53984, ...
    54484, 55733, 55783, 55883, 56883, 56999, 57532, ...
    57966, 58016, 58115, 59432, 60298, 61098, 61114, ...
    61164, 62797, 62880, 62897, 66146, 66229, 66263, ...
    66313, 66712, 66778, 67328, 68012, 69178, 69228, ...
    71627, 73176, 73876, 73909, 73943, 74459, 78225, ...
    78541, 78657, 79374, 79407, 79474, 80274, 80441, ...
    80740, 81040, 81073, 81142, 81756, 81923, 82107, ...
    82607, 82656, 82673, 85355, 85472, 85588, 86538, ...
    86571, 86621, 87237, 87271, 87338, 88287, 88320, ...
    88337, 89254, 89604, 90720, 90753, 91453, 91536, ...
    93502, 93552, 93569, 94135, 94219, 94236, 96084, ...
    96284, 96384, 98401, 98417, 98450, 100749, 100933, ...
    100949, 101599, 101649, 101682, 103048, 103281, ...
    103382, 103448, 105914, 106414, 106447, 106880, ...
    106981, 106997, 107514, 107597, 110129, 110195, ...
    110596, 110629, 110879, 111729, 113561, 113611, ...
    113695, 114228, 114827, 114894, 116594, 117260, ...
    117843, 118693, 118726, 118809];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '04-03-2010 17:40:48';
CurrentBlock.Timestamps.BlockStart= '04-03-2010 17:46:12';
CurrentBlock.Timestamps.BlockEnd= '04-03-2010 17:49:18';
CurrentBlock.Parameters.MasksNumber= 3;
CurrentBlock.Settings.MasksNumber= 3;
CurrentBlock.Parameters.KanitzaIsAligned= 1;
CurrentBlock.Settings.KanitzaIsAligned= 1;
CurrentBlock.Parameters.Subject= '20';
CurrentBlock.Settings.Subject= '20';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 120;
CurrentBlock.Settings.TrialDuration_SEC= 120;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1340];
CurrentBlock.Target= [1, 1, 2, 2, 0, 1, 2, 2, 1, 0, 1, ...
    0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 2, 1, 1, 1, 1, 1, 0, ...
    1, 1, 0, 2, 1, 2, 0, 0, 1, 0, 2, 2, 1, 0, 2, 2, 1, ...
    2, 2, 1, 0, 2, 2, 0, 2, 2, 1, 1, 0, 0, 0, 0, 0, 2, ...
    1, 1, 1, 1, 1, 2, 1, 0, 0, 1, 2, 0, 0, 2, 1, 0, 1, ...
    1, 1, 0, 2, 2, 0, 1, 2, 1, 2, 1, 0, 0, 1, 0, 2, 2, ...
    0, 1, 1, 1, 0, 1, 0, 1, 2, 2, 1, 0, 2, 2, 1, 0, 1, ...
    2, 0, 2, 0, 1, 1, 0, 1, 0, 1, 2, 2, 1, 1, 2, 2, 1, ...
    1, 2, 0, 2, 0, 1, 1, 0, 0, 1, 1, 2, 0, 2, 1, 0, 1, ...
    2, 0, 2, 1, 0, 1, 2, 0, 2, 1, 0, 0, 2, 1, 2, 1, 1, ...
    2, 1, 0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 2, 0, 2, 1, 0, ...
    2, 0, 2, 2, 0, 1, 0, 0, 2, 1, 0];
CurrentBlock.Event= [0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, ...
    0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, ...
    0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, ...
    1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, ...
    1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, ...
    0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, ...
    1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, ...
    0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, ...
    0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, ...
    0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, ...
    1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, ...
    1, 1, 0, 0, 0, 1, 0, 1, 1, 1];
CurrentBlock.Time= [10039, 10356, 12271, 12521, 12955, ...
    13321, 13604, 13838, 13888, 13921, 17220, 17387, ...
    17453, 18369, 18403, 18420, 19803, 21485, 21535, ...
    21568, 21735, 22019, 24884, 24950, 25000, 25034, ...
    25200, 25351, 25367, 25617, 26083, 26116, 26233, ...
    26517, 27283, 27600, 29065, 29249, 29282, 30349, ...
    30365, 30382, 34230, 34530, 37396, 37429, 37546, ...
    37612, 37745, 37762, 38129, 38162, 38495, 38762, ...
    40911, 41061, 42110, 42244, 42943, 43077, 43462, ...
    43960, 44060, 44109, 44260, 44276, 44343, 44576, ...
    44643, 44659, 45976, 46076, 46093, 46126, 46226, ...
    46709, 46726, 46759, 47658, 47775, 48675, 48875, ...
    50524, 51174, 51240, 51257, 53256, 53340, 55006, ...
    55039, 55089, 56039, 58437, 58787, 58805, 59937, ...
    59987, 60004, 65435, 65785, 65868, 65968, 66185, ...
    66201, 68351, 68784, 70666, 70866, 71216, 71449, ...
    71482, 71516, 77214, 77247, 77264, 77464, 77480, ...
    77514, 78946, 78996, 79246, 79263, 81962, 82028, ...
    82445, 82462, 83111, 83179, 83411, 83428, 83795, ...
    83812, 84111, 84628, 84661, 84678, 95440, 95873, ...
    96207, 96240, 97606, 97623, 97890, 98022, 98039, ...
    98056, 98973, 98989, 99039, 100172, 100222, 100271, ...
    102838, 102854, 102904, 103537, 103570, 103587, ...
    104703, 106003, 106119, 106420, 106470, 106520, ...
    106569, 106586, 106636, 107119, 107136, 107152, ...
    108835, 109418, 110635, 110651, 111650, 112184, ...
    112434, 112667, 112851, 112934, 113434, 115399, ...
    115416, 115883, 117266, 117765, 117832, 117898, ...
    118132, 118932, 118981, 118998];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '04-03-2010 17:40:48';
CurrentBlock.Timestamps.BlockStart= '04-03-2010 17:49:18';
CurrentBlock.Timestamps.BlockEnd= '04-03-2010 17:52:14';
CurrentBlock.Parameters.MasksNumber= 3;
CurrentBlock.Settings.MasksNumber= 3;
CurrentBlock.Parameters.KanitzaIsAligned= 0;
CurrentBlock.Settings.KanitzaIsAligned= 0;
CurrentBlock.Parameters.Subject= '20';
CurrentBlock.Settings.Subject= '20';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 120;
CurrentBlock.Settings.TrialDuration_SEC= 120;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1251];
CurrentBlock.Target= [2, 1, 2, 0, 1, 0, 0, 2, 1, 1, 1, ...
    2, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 2, 2, 1, 0, 1, 0, ...
    1, 0, 1, 0, 2, 0, 0, 2, 1, 0, 2, 1, 2, 0, 1, 2, 2, ...
    0, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 2, 1, 0, 1, 0, 2, ...
    1, 2, 1, 0, 2, 2, 0, 0, 2, 0, 1, 2, 1, 2, 2, 0, 2, ...
    0, 2, 0, 1, 1, 2, 0, 1, 2, 2, 2, 2, 2, 1, 0, 1, 2, ...
    1, 2, 1, 0, 0, 1, 2, 0, 2, 0, 1, 1, 2, 2, 2, 2, 2, ...
    2, 2, 2, 0, 1, 2, 2, 1, 0, 0, 1, 2, 0, 1, 2];
CurrentBlock.Event= [0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, ...
    1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, ...
    1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, ...
    0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, ...
    1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, ...
    1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, ...
    1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, ...
    0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1];
CurrentBlock.Time= [21821, 21954, 23221, 23271, 23287, ...
    24753, 25770, 25819, 26219, 26235, 26752, 27202, ...
    27369, 27436, 29234, 29834, 31084, 31117, 33550, ...
    33717, 33816, 33866, 33916, 35549, 35632, 35649, ...
    38531, 38598, 40080, 40098, 41814, 42080, 42480, ...
    42630, 43430, 44246, 44495, 44579, 47128, 47178, ...
    47194, 47312, 47328, 47562, 51443, 51477, 58174, ...
    58190, 60140, 60190, 63189, 66087, 66404, 69853, ...
    70485, 70553, 70652, 71269, 71369, 71386, 78699, ...
    78732, 79166, 79399, 79416, 79915, 80198, 80415, ...
    80432, 80965, 83315, 83348, 83514, 83780, 83797, ...
    84297, 84647, 84697, 86913, 86930, 87679, 87730, ...
    88512, 88679, 91711, 91811, 92178, 92644, 92811, ...
    93094, 93160, 93177, 93610, 93660, 94859, 95010, ...
    97426, 97442, 98809, 99075, 99308, 99691, 102357, ...
    102407, 102840, 102923, 103857, 104140, 104890, ...
    105256, 105639, 106872, 109605, 110487, 110554, ...
    111687, 114686, 114785, 115402, 115901, 115935, ...
    115969, 117851, 119551, 119617, 120000, 120000, ...
    120000];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '04-03-2010 17:40:48';
CurrentBlock.Timestamps.BlockStart= '04-03-2010 17:52:14';
CurrentBlock.Timestamps.BlockEnd= '04-03-2010 17:55:01';
CurrentBlock.Parameters.MasksNumber= 1;
CurrentBlock.Settings.MasksNumber= 1;
CurrentBlock.Parameters.KanitzaIsAligned= 1;
CurrentBlock.Settings.KanitzaIsAligned= 1;
CurrentBlock.Parameters.Subject= '20';
CurrentBlock.Settings.Subject= '20';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 120;
CurrentBlock.Settings.TrialDuration_SEC= 120;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1121];
CurrentBlock.Target= [1, 1, 2, 1, 2, 1, 0, 0, 0, 2, 1, ...
    2, 0, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 1, 0, 0, ...
    1, 2, 0, 2, 0, 1, 0, 2, 2, 2, 2, 0, 0, 2, 1, 2, 0, ...
    1, 0, 2, 1, 2, 1, 0, 2, 1, 0, 0, 2, 1, 0, 0, 2, 2, ...
    0, 0, 1, 1, 0, 1, 1, 0, 0, 2, 2, 0, 1, 1, 1, 2, 0, ...
    2, 1, 0, 2, 0, 1, 2, 1, 0, 1, 2, 2, 1, 1, 2, 0, 2, ...
    1, 0, 0, 0, 2, 2, 0, 1, 0, 1, 1, 2, 2, 1, 1, 0, 0, ...
    1];
CurrentBlock.Event= [0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, ...
    1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, ...
    0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, ...
    0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, ...
    1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, ...
    1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, ...
    1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1];
CurrentBlock.Time= [8490, 8540, 9606, 9756, 9789, 9989, ...
    10122, 10372, 10722, 11006, 11089, 11372, 11455, ...
    11471, 20419, 20851, 32797, 32997, 40277, 40427, ...
    40744, 40760, 41926, 41994, 42343, 42360, 44759, ...
    46075, 57005, 57038, 57054, 58654, 58671, 58704, ...
    60753, 60769, 60786, 61087, 61302, 61337, 62885, ...
    62919, 62968, 64502, 64535, 64551, 66551, 66584, ...
    66717, 68017, 68084, 68150, 70166, 70283, 70300, ...
    70432, 70566, 70633, 71366, 72265, 72282, 73282, ...
    73448, 73498, 73898, 73915, 78096, 78729, 78880, ...
    81395, 84444, 85610, 86426, 86509, 91758, 92625, ...
    94324, 94440, 94473, 97056, 97090, 97123, 100637, ...
    100672, 100738, 102154, 102187, 102220, 103370, ...
    103421, 103872, 103920, 104769, 104837, 105186, ...
    106786, 106852, 106869, 108335, 109168, 110567, ...
    112217, 114599, 114666, 115149, 115166, 117115, ...
    117299, 117648, 117681, 119465, 119847, 120000, ...
    120000];
Block{length(Block)+1}= CurrentBlock;

