%%  Experimental log file generated by CLog2 class
%  2009 Alexander Pastukhov (pastukhov.alexander@gmail.com)
%  For uploading into matlab just run it as a script.
%  It will generate an array of structures Block(N), where N is number of blocks
%  Settings for each block are in .Settings substructure
%  Parameters (settings which define different conditions) are in substructure .Parameters
%  Data specific for individual trials is in .Trial(M) substructure, where M is number of trials
Block= [];

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '15-02-2010 18:19:19';
CurrentBlock.Timestamps.BlockStart= '15-02-2010 18:19:23';
CurrentBlock.Timestamps.BlockEnd= '15-02-2010 18:19:58';
CurrentBlock.Parameters.MasksNumber= 1;
CurrentBlock.Settings.MasksNumber= 1;
CurrentBlock.Parameters.KanitzaIsAligned= 0;
CurrentBlock.Settings.KanitzaIsAligned= 0;
CurrentBlock.Parameters.Subject= '02';
CurrentBlock.Settings.Subject= '02';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 30;
CurrentBlock.Settings.TrialDuration_SEC= 30;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1070];
CurrentBlock.Target= [0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, ...
    1, 1, 0, 0, 0, 0, 0, 0, 1, 2, 1, 2, 0, 0, 0];
CurrentBlock.Event= [0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, ...
    1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1];
CurrentBlock.Time= [9490, 9656, 10323, 10573, 12388, ...
    12755, 13172, 13188, 15371, 15838, 18019, 18053, ...
    18736, 18769, 21901, 22551, 24117, 24883, 27283, ...
    27316, 27333, 27733, 27766, 27783, 29882, 30000];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '15-02-2010 18:19:19';
CurrentBlock.Timestamps.BlockStart= '15-02-2010 18:19:58';
CurrentBlock.Timestamps.BlockEnd= '15-02-2010 18:20:31';
CurrentBlock.Parameters.MasksNumber= 3;
CurrentBlock.Settings.MasksNumber= 3;
CurrentBlock.Parameters.KanitzaIsAligned= 1;
CurrentBlock.Settings.KanitzaIsAligned= 1;
CurrentBlock.Parameters.Subject= '02';
CurrentBlock.Settings.Subject= '02';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 30;
CurrentBlock.Settings.TrialDuration_SEC= 30;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1103];
CurrentBlock.Target= [0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, ...
    0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, ...
    0, 1, 1, 0, 0, 1, 0, 1];
CurrentBlock.Event= [0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, ...
    0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, ...
    0, 1, 1, 0, 0, 1, 1];
CurrentBlock.Time= [8189, 8321, 8955, 8972, 9189, 9638, ...
    10621, 10921, 11188, 11587, 11870, 11887, 12804, ...
    13403, 14503, 14736, 17519, 17818, 20051, 20068, ...
    21017, 21033, 22600, 22616, 23116, 23133, 24516, ...
    24865, 25782, 26382, 26698, 26715, 28530, 28614, ...
    28848, 28864];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '15-02-2010 18:19:19';
CurrentBlock.Timestamps.BlockStart= '15-02-2010 18:20:31';
CurrentBlock.Timestamps.BlockEnd= '15-02-2010 18:21:06';
CurrentBlock.Parameters.MasksNumber= 3;
CurrentBlock.Settings.MasksNumber= 3;
CurrentBlock.Parameters.KanitzaIsAligned= 0;
CurrentBlock.Settings.KanitzaIsAligned= 0;
CurrentBlock.Parameters.Subject= '02';
CurrentBlock.Settings.Subject= '02';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 30;
CurrentBlock.Settings.TrialDuration_SEC= 30;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1378];
CurrentBlock.Target= [1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, ...
    1, 1, 1, 0, 0, 1, 1];
CurrentBlock.Event= [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, ...
    0, 1, 0, 1, 0, 1];
CurrentBlock.Time= [10191, 10924, 17404, 17855, 19221, ...
    19870, 20036, 20203, 20420, 20486, 22652, 22769, ...
    25185, 25468, 28434, 28600, 29050, 29200];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '15-02-2010 18:19:19';
CurrentBlock.Timestamps.BlockStart= '15-02-2010 18:21:06';
CurrentBlock.Timestamps.BlockEnd= '15-02-2010 18:21:41';
CurrentBlock.Parameters.MasksNumber= 1;
CurrentBlock.Settings.MasksNumber= 1;
CurrentBlock.Parameters.KanitzaIsAligned= 1;
CurrentBlock.Settings.KanitzaIsAligned= 1;
CurrentBlock.Parameters.Subject= '02';
CurrentBlock.Settings.Subject= '02';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 30;
CurrentBlock.Settings.TrialDuration_SEC= 30;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1499];
CurrentBlock.Target= [1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, ...
    1, 2, 2, 0, 0, 1, 1, 2, 2, 1, 1, 1, 0, 2, 1, 2, 0, ...
    1, 0, 2, 1, 0, 2];
CurrentBlock.Event= [0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, ...
    0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, ...
    0, 0, 1, 1, 1];
CurrentBlock.Time= [6790, 6806, 7090, 7106, 9489, 9722, ...
    12188, 12221, 12387, 12421, 13470, 13604, 14936, ...
    15137, 17036, 17203, 17636, 17769, 19518, 19719, ...
    21068, 21168, 26083, 26099, 26116, 26182, 26549, ...
    26600, 28481, 28498, 28515, 28681, 28715, 28731];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '15-02-2010 18:19:19';
CurrentBlock.Timestamps.BlockStart= '15-02-2010 18:21:41';
CurrentBlock.Timestamps.BlockEnd= '15-02-2010 18:23:47';
CurrentBlock.Parameters.MasksNumber= 1;
CurrentBlock.Settings.MasksNumber= 1;
CurrentBlock.Parameters.KanitzaIsAligned= 0;
CurrentBlock.Settings.KanitzaIsAligned= 0;
CurrentBlock.Parameters.Subject= '02';
CurrentBlock.Settings.Subject= '02';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 120;
CurrentBlock.Settings.TrialDuration_SEC= 120;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1258];
CurrentBlock.Target= [1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, ...
    0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 2, 1, ...
    2, 0, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 2, 0, 2, 0, 1, ...
    1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 2, 1, 2, 0, ...
    0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 2, 0, 1, 1, 2, 0, 1, ...
    1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, ...
    0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 2, 2, 1, 0, 1, 0, 1, ...
    0, 1, 1, 2, 2, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, ...
    2, 2, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0];
CurrentBlock.Event= [0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, ...
    1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, ...
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, ...
    0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, ...
    1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, ...
    0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, ...
    1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, ...
    0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, ...
    1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1];
CurrentBlock.Time= [7364, 7897, 9947, 9963, 10246, ...
    10263, 12479, 12562, 13045, 13062, 15195, 15861, ...
    15877, 16344, 18443, 18760, 18860, 18943, 20492, ...
    20675, 21758, 22109, 23192, 24158, 24207, 24691, ...
    24824, 25074, 25090, 25107, 26540, 26690, 27856, ...
    28006, 31121, 31338, 32804, 32938, 33420, 33604, ...
    34337, 34354, 34520, 34536, 35670, 35786, 37252, ...
    37669, 40201, 40418, 42151, 42184, 42434, 42450, ...
    43717, 44216, 46049, 46099, 46116, 46366, 46382, ...
    46415, 50764, 50898, 54063, 54179, 54213, 54396, ...
    58661, 58895, 61694, 61860, 63292, 63309, 63325, ...
    63426, 63443, 63459, 65042, 65258, 66125, 66158, ...
    66325, 66374, 69540, 70007, 71073, 71140, 71339, ...
    71440, 75488, 75522, 75721, 75738, 77870, 78021, ...
    83185, 83269, 87933, 88050, 90299, 90483, 90632, ...
    90649, 92664, 92699, 92715, 92765, 92782, 92815, ...
    96147, 96163, 96364, 96380, 99545, 99696, 102094, ...
    102228, 104293, 104310, 104460, 104510, 107009, ...
    107159, 107292, 107325, 110175, 110308, 113357, ...
    113407, 113440, 113457, 113491, 113507, 116122, ...
    116273, 116689, 116823, 119005, 119072, 119322, ...
    119338];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '15-02-2010 18:19:19';
CurrentBlock.Timestamps.BlockStart= '15-02-2010 18:23:47';
CurrentBlock.Timestamps.BlockEnd= '15-02-2010 18:25:51';
CurrentBlock.Parameters.MasksNumber= 3;
CurrentBlock.Settings.MasksNumber= 3;
CurrentBlock.Parameters.KanitzaIsAligned= 1;
CurrentBlock.Settings.KanitzaIsAligned= 1;
CurrentBlock.Parameters.Subject= '02';
CurrentBlock.Settings.Subject= '02';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 120;
CurrentBlock.Settings.TrialDuration_SEC= 120;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1148];
CurrentBlock.Target= [1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, ...
    0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, ...
    1, 1, 0, 0, 0, 2, 1, 2, 1, 0, 1, 1, 0, 0, 1, 1, 1, ...
    1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 2, 2, 0, 0, 1, 0, 1, ...
    0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 2, 1, 2, ...
    0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, ...
    0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0];
CurrentBlock.Event= [0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, ...
    0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, ...
    1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, ...
    0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, ...
    1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, ...
    0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, ...
    1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1];
CurrentBlock.Time= [11670, 11804, 15386, 15485, 18385, ...
    18517, 21516, 21849, 23633, 23649, 24132, 24148, ...
    27081, 27248, 28580, 28747, 30047, 30163, 30779, ...
    30796, 30946, 30963, 33362, 33495, 35012, 35411, ...
    36893, 37027, 38943, 39093, 39326, 39443, 42075, ...
    42092, 42108, 42209, 42225, 42259, 44958, 45107, ...
    46940, 47156, 50772, 50872, 53721, 53854, 56353, ...
    56470, 59185, 59285, 59818, 59952, 61251, 61684, ...
    65383, 65416, 65583, 65599, 67699, 67749, 67882, ...
    67898, 69865, 69998, 70764, 70798, 70914, 70930, ...
    72513, 72530, 72647, 72680, 74013, 74396, 76478, ...
    76496, 76529, 76712, 76728, 76745, 80011, 80211, ...
    84142, 84343, 85908, 86641, 88425, 88591, 89640, ...
    89806, 91956, 92090, 94272, 94455, 98787, 98987, ...
    100869, 101003, 102435, 102652, 105184, 105368, ...
    113931, 114131, 114281, 114314, 117096, 117263, ...
    118613, 118646, 118779, 118812];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '15-02-2010 18:19:19';
CurrentBlock.Timestamps.BlockStart= '15-02-2010 18:25:51';
CurrentBlock.Timestamps.BlockEnd= '15-02-2010 18:27:57';
CurrentBlock.Parameters.MasksNumber= 3;
CurrentBlock.Settings.MasksNumber= 3;
CurrentBlock.Parameters.KanitzaIsAligned= 0;
CurrentBlock.Settings.KanitzaIsAligned= 0;
CurrentBlock.Parameters.Subject= '02';
CurrentBlock.Settings.Subject= '02';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 120;
CurrentBlock.Settings.TrialDuration_SEC= 120;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1197];
CurrentBlock.Target= [1, 1, 0, 0, 0, 0, 0, 2, 1, 1, 2, ...
    0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, ...
    2, 2, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, ...
    1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0];
CurrentBlock.Event= [0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, ...
    0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, ...
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, ...
    0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1];
CurrentBlock.Time= [12785, 12937, 14502, 14668, 16851, ...
    17001, 19600, 19633, 19650, 19683, 19716, 19750, ...
    55903, 55919, 56086, 56119, 62000, 62167, 63817, ...
    64533, 64683, 64799, 66582, 66616, 67449, 67465, ...
    69264, 69830, 69948, 70198, 70547, 70797, 71630, ...
    72230, 73596, 73912, 76744, 76945, 77411, 77594, ...
    78811, 79044, 81209, 81426, 81577, 81709, 98886, ...
    99419, 111482, 111498, 111581, 111615, 113764, ...
    113898, 118029, 118045, 118146, 118179];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '15-02-2010 18:19:19';
CurrentBlock.Timestamps.BlockStart= '15-02-2010 18:27:57';
CurrentBlock.Timestamps.BlockEnd= '15-02-2010 18:30:02';
CurrentBlock.Parameters.MasksNumber= 1;
CurrentBlock.Settings.MasksNumber= 1;
CurrentBlock.Parameters.KanitzaIsAligned= 1;
CurrentBlock.Settings.KanitzaIsAligned= 1;
CurrentBlock.Parameters.Subject= '02';
CurrentBlock.Settings.Subject= '02';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 120;
CurrentBlock.Settings.TrialDuration_SEC= 120;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1260];
CurrentBlock.Target= [1, 1, 1, 0, 2, 1, 2, 0, 1, 0, 1, ...
    0, 0, 1, 0, 1, 1, 1, 1, 0, 2, 1, 0, 2, 1, 1, 0, 0, ...
    0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 2, 1, 2, 1, 0, 1, ...
    0, 0, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 0, 0, 1, 1, 0, ...
    1, 1, 1, 1, 2, 0, 1, 1, 2, 0, 0, 0, 1, 0, 0, 1, 1, ...
    1, 0, 0, 1, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 0, 1, 1, ...
    0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 2, 1, ...
    1, 2, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, ...
    1, 0, 2, 1, 2, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, ...
    1, 1, 1, 0, 2, 2, 0, 1, 1, 0, 0, 2, 2, 0, 0, 0, 1, ...
    1, 0, 0, 1, 0, 1, 1, 1, 0, 0];
CurrentBlock.Event= [0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, ...
    0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, ...
    1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, ...
    0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, ...
    1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, ...
    0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, ...
    0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, ...
    1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, ...
    0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, ...
    0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, ...
    1, 0, 0, 1, 1, 0, 1, 0, 1];
CurrentBlock.Time= [6789, 6955, 11103, 11221, 11237, ...
    11420, 11437, 11454, 14203, 14352, 14569, 14586, ...
    16934, 17018, 17385, 17401, 18817, 19101, 21583, ...
    21616, 21633, 21783, 21800, 21816, 23133, 23266, ...
    24632, 24766, 25065, 25182, 25565, 25599, 25665, ...
    25715, 27147, 27181, 27381, 27397, 28230, 28247, ...
    28297, 28464, 30229, 31097, 31496, 31513, 33278, ...
    33612, 34212, 34345, 35128, 35295, 35545, 35644, ...
    35678, 35845, 35861, 35894, 37511, 37610, 37710, ...
    37777, 40459, 40642, 43575, 43758, 45707, 45740, ...
    45757, 45841, 45857, 45874, 47656, 47856, 49223, ...
    49239, 49423, 49439, 51838, 52038, 54687, 54870, ...
    61118, 61135, 61318, 61335, 61718, 61751, 61767, ...
    61851, 61885, 61901, 64566, 64733, 65066, 65200, ...
    67116, 67133, 67249, 67282, 68998, 69032, 69165, ...
    69182, 72947, 72980, 73097, 73113, 75463, 75579, ...
    79227, 79244, 79278, 79428, 79444, 79477, 81810, ...
    81960, 84226, 84309, 84476, 84509, 86075, 86108, ...
    86292, 86309, 88058, 88191, 90606, 90823, 93822, ...
    93855, 93889, 94022, 94039, 94056, 98887, 99020, ...
    100120, 100137, 100286, 100304, 102036, 102069, ...
    102203, 102235, 103018, 103169, 104351, 104485, ...
    106468, 106501, 106701, 106751, 107517, 107667, ...
    109850, 110017, 110466, 110633, 112998, 113182, ...
    113415, 113432, 113531, 113564, 115048, 115081, ...
    115214, 115230, 116580, 116681, 117996, 118146];
Block{length(Block)+1}= CurrentBlock;

