%%  Experimental log file generated by CLog2 class
%  2009 Alexander Pastukhov (pastukhov.alexander@gmail.com)
%  For uploading into matlab just run it as a script.
%  It will generate an array of structures Block(N), where N is number of blocks
%  Settings for each block are in .Settings substructure
%  Parameters (settings which define different conditions) are in substructure .Parameters
%  Data specific for individual trials is in .Trial(M) substructure, where M is number of trials
Block= [];

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '26-02-2010 16:50:30';
CurrentBlock.Timestamps.BlockStart= '26-02-2010 16:51:04';
CurrentBlock.Timestamps.BlockEnd= '26-02-2010 16:51:44';
CurrentBlock.Parameters.MasksNumber= 1;
CurrentBlock.Settings.MasksNumber= 1;
CurrentBlock.Parameters.KanitzaIsAligned= 0;
CurrentBlock.Settings.KanitzaIsAligned= 0;
CurrentBlock.Parameters.Subject= '18';
CurrentBlock.Settings.Subject= '18';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 30;
CurrentBlock.Settings.TrialDuration_SEC= 30;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1385];
CurrentBlock.Target= [2, 2, 2, 2, 2, 0, 2, 1, 0, 1, 2, ...
    0, 1, 2, 0, 1, 2, 2, 2, 2, 0, 0, 1, 2, 1, 0, 2, 0, ...
    0, 1, 2, 0, 2, 1];
CurrentBlock.Event= [0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, ...
    0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, ...
    0, 0, 1, 1, 1];
CurrentBlock.Time= [4619, 5202, 7185, 7735, 7951, 7985, ...
    8135, 8268, 8701, 9301, 14832, 15049, 15066, 15816, ...
    16048, 16115, 16382, 16515, 16765, 16965, 16998, ...
    17465, 19814, 21446, 21463, 21546, 22079, 22096, ...
    28127, 28693, 29061, 29543, 29560, 29593];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '26-02-2010 16:50:30';
CurrentBlock.Timestamps.BlockStart= '26-02-2010 16:51:44';
CurrentBlock.Timestamps.BlockEnd= '26-02-2010 16:52:26';
CurrentBlock.Parameters.MasksNumber= 3;
CurrentBlock.Settings.MasksNumber= 3;
CurrentBlock.Parameters.KanitzaIsAligned= 1;
CurrentBlock.Settings.KanitzaIsAligned= 1;
CurrentBlock.Parameters.Subject= '18';
CurrentBlock.Settings.Subject= '18';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 30;
CurrentBlock.Settings.TrialDuration_SEC= 30;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1042];
CurrentBlock.Target= [1, 2, 1, 1, 1, 2, 0, 0, 2, 1, 2, ...
    2, 0, 2, 0, 1, 2, 0, 2, 0, 1, 0, 2, 1, 1, 0, 2, 1, ...
    0, 0, 1, 2, 0, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2, 0, 1, ...
    0, 2, 1, 1, 1, 1, 0, 2, 1, 0, 2];
CurrentBlock.Event= [0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, ...
    0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, ...
    1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, ...
    1, 1, 0, 1, 0, 0, 0, 1, 1, 1];
CurrentBlock.Time= [3018, 4434, 4617, 5051, 5450, 5484, ...
    5967, 6633, 6750, 6800, 6817, 7017, 7050, 7782, ...
    7799, 7817, 10965, 11664, 11982, 12015, 13948, ...
    14930, 15031, 15163, 15496, 15813, 15847, 15864, ...
    17462, 17912, 18329, 18646, 18779, 19429, 19446, ...
    19462, 20612, 21145, 21645, 22094, 22127, 22160, ...
    23577, 23977, 24126, 24576, 25310, 25326, 26809, ...
    27425, 27609, 29608, 29907, 29958, 30000, 30000];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '26-02-2010 16:50:30';
CurrentBlock.Timestamps.BlockStart= '26-02-2010 16:52:26';
CurrentBlock.Timestamps.BlockEnd= '26-02-2010 16:53:01';
CurrentBlock.Parameters.MasksNumber= 3;
CurrentBlock.Settings.MasksNumber= 3;
CurrentBlock.Parameters.KanitzaIsAligned= 0;
CurrentBlock.Settings.KanitzaIsAligned= 0;
CurrentBlock.Parameters.Subject= '18';
CurrentBlock.Settings.Subject= '18';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 30;
CurrentBlock.Settings.TrialDuration_SEC= 30;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1331];
CurrentBlock.Target= [1, 2, 1, 2, 0, 0, 1, 2, 0, 0, 2, ...
    1, 0, 1, 0, 1, 2, 1, 1, 2, 0, 0, 2, 2, 1, 2, 0, 0, ...
    1, 2, 1, 2, 0, 0, 1, 2, 2, 0, 1, 0, 1, 2, 0, 2, 0, ...
    2, 0, 1, 2, 0, 1, 2];
CurrentBlock.Event= [0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, ...
    0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, ...
    1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, ...
    0, 0, 0, 1, 1, 1];
CurrentBlock.Time= [1499, 1715, 3215, 3248, 3864, 4564, ...
    6580, 6780, 7013, 7529, 8279, 8346, 9679, 10129, ...
    10679, 10695, 12161, 12744, 14160, 14244, 14443, ...
    15060, 15094, 15276, 15326, 16526, 16559, 17259, ...
    17275, 17293, 19975, 20125, 20158, 20791, 22240, ...
    22308, 23856, 23873, 24040, 24923, 24939, 24973, ...
    26322, 27022, 28055, 28305, 29354, 29555, 29888, ...
    30000, 30000, 30000];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '26-02-2010 16:50:30';
CurrentBlock.Timestamps.BlockStart= '26-02-2010 16:53:01';
CurrentBlock.Timestamps.BlockEnd= '26-02-2010 16:53:45';
CurrentBlock.Parameters.MasksNumber= 1;
CurrentBlock.Settings.MasksNumber= 1;
CurrentBlock.Parameters.KanitzaIsAligned= 1;
CurrentBlock.Settings.KanitzaIsAligned= 1;
CurrentBlock.Parameters.Subject= '18';
CurrentBlock.Settings.Subject= '18';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 30;
CurrentBlock.Settings.TrialDuration_SEC= 30;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1300];
CurrentBlock.Target= [2, 2, 2, 0, 1, 0, 1, 2, 2, 1, 2, ...
    1, 2, 1, 1, 2, 1, 0, 2, 0, 1, 2, 2, 2, 2, 2, 2, 1, ...
    1, 2, 1, 1, 2, 2, 1, 2, 1, 2];
CurrentBlock.Event= [0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, ...
    0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, ...
    1, 0, 1, 0, 1, 0, 0, 1, 1];
CurrentBlock.Time= [1318, 1784, 3134, 3567, 3734, 4283, ...
    4517, 4533, 7032, 7266, 7849, 7865, 9664, 9864, ...
    10814, 11080, 12180, 12663, 13546, 14079, 14096, ...
    14129, 16895, 17595, 19677, 20194, 24509, 24625, ...
    25292, 25309, 26359, 26841, 27674, 28174, 29840, ...
    29873, 30000, 30000];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '26-02-2010 16:50:30';
CurrentBlock.Timestamps.BlockStart= '26-02-2010 16:53:45';
CurrentBlock.Timestamps.BlockEnd= '26-02-2010 16:55:51';
CurrentBlock.Parameters.MasksNumber= 1;
CurrentBlock.Settings.MasksNumber= 1;
CurrentBlock.Parameters.KanitzaIsAligned= 0;
CurrentBlock.Settings.KanitzaIsAligned= 0;
CurrentBlock.Parameters.Subject= '18';
CurrentBlock.Settings.Subject= '18';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 120;
CurrentBlock.Settings.TrialDuration_SEC= 120;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1432];
CurrentBlock.Target= [1, 2, 2, 1, 2, 2, 2, 2, 1, 0, 2, ...
    0, 2, 1, 2, 2, 1, 2, 0, 0, 2, 1, 2, 2, 1, 1, 2, 1, ...
    2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 0, 0, 1, 1, 2, 1, 0, ...
    2, 0, 1, 2, 1, 0, 2, 0, 1, 0, 1, 2, 2, 0, 1, 1, 2, ...
    0, 2, 0, 1, 0, 1, 0, 1, 1, 0, 2, 0, 2, 1, 1, 2, 0, ...
    0, 2, 1, 1, 0, 0, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, ...
    1, 2, 0, 2, 0, 1, 0, 2, 2, 0, 2, 0, 2, 0, 1, 1, 2, ...
    1, 2, 1, 2, 2, 1, 0, 2, 0, 2, 1, 0, 0, 1, 1, 0, 1, ...
    0, 1, 2, 1, 0, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 0];
CurrentBlock.Event= [0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, ...
    1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, ...
    1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, ...
    1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, ...
    1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, ...
    1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, ...
    0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, ...
    1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, ...
    1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1];
CurrentBlock.Time= [3765, 4131, 5031, 5081, 6830, 7314, ...
    8980, 9846, 11295, 11578, 11878, 12378, 12395, ...
    12411, 14528, 15127, 16876, 16909, 17543, 17959, ...
    18159, 18176, 21491, 22058, 25374, 25989, 26939, ...
    27422, 27922, 27939, 30272, 30572, 31405, 31521, ...
    33270, 33703, 34336, 34770, 35752, 36035, 38302, ...
    39235, 40617, 40818, 41234, 41783, 41800, 41817, ...
    44233, 44249, 44400, 45049, 45066, 45082, 46682, ...
    46915, 46932, 47548, 47565, 47581, 49448, 49464, ...
    49564, 50198, 50231, 50247, 51413, 51680, 52296, ...
    52329, 54279, 54545, 54912, 55463, 55961, 56011, ...
    57744, 57778, 58061, 58727, 58960, 58977, 60709, ...
    60727, 61593, 61626, 63309, 63875, 70039, 70523, ...
    71372, 71455, 74804, 75771, 77453, 78836, 81185, ...
    81219, 81352, 81652, 81668, 81718, 83468, 83884, ...
    84268, 84301, 85401, 85783, 86083, 86150, 86883, ...
    87583, 89932, 90382, 90831, 90848, 92247, 92997, ...
    99661, 99895, 100145, 100596, 100612, 100628, ...
    103626, 104643, 106143, 106776, 108625, 108741, ...
    109291, 109624, 110707, 110790, 110823, 111391, ...
    111407, 111457, 115356, 116122, 116573, 117005, ...
    118254, 118938, 118954, 119304];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '26-02-2010 16:50:30';
CurrentBlock.Timestamps.BlockStart= '26-02-2010 16:55:51';
CurrentBlock.Timestamps.BlockEnd= '26-02-2010 16:58:43';
CurrentBlock.Parameters.MasksNumber= 3;
CurrentBlock.Settings.MasksNumber= 3;
CurrentBlock.Parameters.KanitzaIsAligned= 1;
CurrentBlock.Settings.KanitzaIsAligned= 1;
CurrentBlock.Parameters.Subject= '18';
CurrentBlock.Settings.Subject= '18';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 120;
CurrentBlock.Settings.TrialDuration_SEC= 120;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1461];
CurrentBlock.Target= [1, 1, 2, 0, 0, 2, 2, 2, 0, 0, 1, ...
    2, 2, 1, 1, 1, 1, 0, 2, 2, 0, 1, 2, 2, 2, 1, 0, 0, ...
    2, 1, 2, 1, 2, 1, 2, 0, 0, 2, 2, 2, 0, 0, 0, 0, 2, ...
    1, 0, 2, 0, 1, 0, 1, 0, 1, 0, 0, 2, 1, 0, 2, 0, 1, ...
    2, 1, 0, 0, 2, 1, 2, 0, 1, 0, 2, 1, 2, 1, 0, 2, 1, ...
    0, 2, 1, 0, 0, 1, 2, 2, 1, 0, 2, 0, 1, 2, 2, 2, 1, ...
    0, 2, 0, 1, 2, 2, 2, 0, 1, 2, 0, 1, 2, 1, 0, 0, 1, ...
    2, 2, 1, 0, 2, 0, 1, 2, 1, 0, 2, 0, 1, 2, 0, 1, 2, ...
    0, 1, 2, 0, 2, 0, 1, 0, 0, 1, 2, 0, 1, 0, 2, 1, 2, ...
    1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2, 0, ...
    1, 0, 2, 1, 2, 0, 2, 0, 2, 0, 2, 0, 1, 0, 0, 1, 2, ...
    1, 0, 2, 0, 1];
CurrentBlock.Event= [0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, ...
    1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, ...
    1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, ...
    0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, ...
    0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, ...
    0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, ...
    1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, ...
    0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, ...
    1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, ...
    1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, ...
    1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, ...
    0, 1, 1, 1];
CurrentBlock.Time= [2627, 3059, 3892, 4609, 4925, 4942, ...
    7274, 7691, 8491, 8557, 8624, 9041, 9357, 9374, ...
    11257, 11656, 14355, 15172, 15405, 15505, 15588, ...
    15755, 17271, 17854, 19220, 19254, 20320, 20686, ...
    21019, 21319, 22718, 23169, 23685, 23718, 26817, ...
    26867, 27417, 27450, 28599, 28900, 28950, 29233, ...
    29932, 30866, 31732, 31882, 31949, 32915, 32931, ...
    32948, 36830, 37146, 37830, 37880, 39446, 40195, ...
    41145, 41478, 41511, 42311, 42344, 42444, 44610, ...
    44660, 44794, 46809, 46826, 46859, 48242, 48276, ...
    48293, 49675, 49975, 50025, 51941, 51958, 51991, ...
    53440, 53457, 53490, 55106, 55123, 55173, 56289, ...
    56324, 56522, 58605, 58672, 58789, 59188, 60621, ...
    60687, 61720, 62454, 64653, 64686, 64769, 65203, ...
    65253, 65286, 67485, 68285, 69534, 69601, 69634, ...
    70300, 70334, 70383, 72383, 72466, 72500, 73916, ...
    74132, 74149, 76065, 76082, 76115, 77215, 77248, ...
    77264, 80730, 80797, 80830, 82496, 82529, 82596, ...
    84012, 84178, 85278, 85712, 85728, 85761, 87878, ...
    88128, 89226, 89310, 91026, 91342, 92359, 92475, ...
    94275, 94358, 94724, 95408, 95424, 95474, 96807, ...
    96841, 97424, 97473, 99656, 99706, 100239, 100305, ...
    102488, 102971, 103771, 103788, 106020, 107186, ...
    107219, 107486, 108319, 108386, 108620, 109286, ...
    109302, 109319, 110569, 111202, 111519, 111568, ...
    113451, 113701, 114017, 114034, 114784, 115383, ...
    115850, 115883, 117083, 117299, 117382, 118216, ...
    118232, 118482];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '26-02-2010 16:50:30';
CurrentBlock.Timestamps.BlockStart= '26-02-2010 16:58:43';
CurrentBlock.Timestamps.BlockEnd= '26-02-2010 17:00:59';
CurrentBlock.Parameters.MasksNumber= 3;
CurrentBlock.Settings.MasksNumber= 3;
CurrentBlock.Parameters.KanitzaIsAligned= 0;
CurrentBlock.Settings.KanitzaIsAligned= 0;
CurrentBlock.Parameters.Subject= '18';
CurrentBlock.Settings.Subject= '18';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 120;
CurrentBlock.Settings.TrialDuration_SEC= 120;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1231];
CurrentBlock.Target= [1, 1, 1, 0, 0, 1, 2, 1, 2, 1, 0, ...
    1, 2, 0, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 2, 0, 2, 1, ...
    0, 0, 2, 1, 0, 0, 2, 1, 1, 0, 0, 1, 0, 2, 1, 2, 0, ...
    1, 0, 2, 1, 2, 0, 1, 1, 0, 0, 1, 2, 1, 2, 1, 0, 2, ...
    1, 0, 2, 1, 2, 2, 2, 1, 0, 2, 0, 1, 1, 0, 2, 2, 0, ...
    1, 1, 2, 0, 2, 0, 1, 0, 1, 0, 1, 2, 1, 2, 1, 2, 0, ...
    1, 0, 2, 1, 1, 1, 0, 2, 1, 0, 2, 1];
CurrentBlock.Event= [0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, ...
    0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, ...
    1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, ...
    0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, ...
    1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, ...
    0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, ...
    1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1];
CurrentBlock.Time= [3004, 3403, 6252, 6436, 7151, 7218, ...
    7935, 8135, 9768, 9817, 10567, 11333, 11417, 12466, ...
    12933, 12966, 14349, 15132, 16831, 16881, 20763, ...
    21812, 30393, 30442, 30459, 31409, 31643, 31676, ...
    34058, 34975, 35940, 36240, 36424, 37490, 37939, ...
    38007, 56999, 57133, 57616, 57633, 62114, 62681, ...
    63014, 63514, 63530, 63563, 64580, 64697, 64729, ...
    65312, 65363, 65380, 66728, 67612, 68162, 68195, ...
    69161, 69595, 70161, 70194, 72144, 72294, 72360, ...
    73560, 73576, 73626, 76825, 77458, 81606, 81689, ...
    81724, 83106, 83123, 83173, 99733, 100149, 100399, ...
    100982, 100999, 101032, 103215, 103250, 103332, ...
    103865, 103882, 103898, 105081, 105314, 105781, ...
    105831, 109146, 109680, 110379, 110395, 113012, ...
    113045, 113095, 113711, 113728, 113777, 116243, ...
    116927, 118176, 118209, 118243, 119426, 119442, ...
    119459];
Block{length(Block)+1}= CurrentBlock;

%%-----------------------------------------------------------------------
clear CurrentBlock;
CurrentBlock.Timestamps.SessionStart= '26-02-2010 16:50:30';
CurrentBlock.Timestamps.BlockStart= '26-02-2010 17:00:59';
CurrentBlock.Timestamps.BlockEnd= '26-02-2010 17:04:48';
CurrentBlock.Parameters.MasksNumber= 1;
CurrentBlock.Settings.MasksNumber= 1;
CurrentBlock.Parameters.KanitzaIsAligned= 1;
CurrentBlock.Settings.KanitzaIsAligned= 1;
CurrentBlock.Parameters.Subject= '18';
CurrentBlock.Settings.Subject= '18';
CurrentBlock.Settings.Trials= 1;
CurrentBlock.Parameters.TrialDuration_SEC= 120;
CurrentBlock.Settings.TrialDuration_SEC= 120;
CurrentBlock.Settings.MaxDelayBeforeTrial= 1500;
CurrentBlock.Settings.MinDelayBeforeTrial= 1000;
CurrentBlock.Settings.BreakBetweenBlocksInSeconds= 0;
CurrentBlock.Settings.LuminancePath= 'Common/Calibration';
CurrentBlock.Settings.screenName= 'ibio34';
CurrentBlock.Settings.screenBackgroundLuminance= 0.3;
CurrentBlock.Settings.screenWidth= 1280;
CurrentBlock.Settings.screenHeight= 1024;
CurrentBlock.Settings.screenFullScreen= 1;
CurrentBlock.Settings.screenFont= 'Common/fonts/times.ttf';
CurrentBlock.Settings.screenFPS= 75;
CurrentBlock.Settings.screenPixelsPerDegree= 86;
CurrentBlock.Settings.screenStereo= 0;
CurrentBlock.Settings.screenAnaglyph= 0;
CurrentBlock.Settings.fixationOuterRadius= 5;
CurrentBlock.Settings.fixationInnerRadius= 3;
CurrentBlock.Settings.fixationApertureRadius= 0;
CurrentBlock.Settings.fixationColor= [1 1 1];
CurrentBlock.Settings.fixationApertureColor= [0.3];
CurrentBlock.Settings.fixationBlend= 0;
CurrentBlock.Settings.fixationLineWidth= 2;
CurrentBlock.Settings.packmanRadius= 18;
CurrentBlock.Settings.packmanApertureRadius= 20;
CurrentBlock.Settings.packmanColor= [1 1 0];
CurrentBlock.Settings.packmanCutOutDegrees= 60;
CurrentBlock.Settings.kanizsaRadius= 100;
CurrentBlock.Settings.kanizsaOrientationDeg= 270;
CurrentBlock.Settings.kanizsaAlignment= [0 0 0];
CurrentBlock.Settings.kanizsaMisalignment= [45 45 45];
CurrentBlock.Settings.mibGridN= 15;
CurrentBlock.Settings.mibGridStep= 35;
CurrentBlock.Settings.mibGridCrossWidth= 20;
CurrentBlock.Settings.mibGridCrossThickness= 3;
CurrentBlock.Settings.mibGridColor= [0 0 1];
CurrentBlock.Settings.mibGridRotationSpeedHz= -0.5;
CurrentBlock.Settings.mibGridCircular= 1;
CurrentBlock.Settings.mib3GridN= 9;
CurrentBlock.Settings.mib3GridEccentricity= 175;
CurrentBlock.Settings.mib3GridCircular= 1;
CurrentBlock.TrialDelay= [1069];
CurrentBlock.Target= [1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, ...
    1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, ...
    1, 2, 2, 1, 2, 1, 2, 2, 2, 1, 0, 1, 2, 0, 2, 1, 1, ...
    1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, ...
    2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, ...
    1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, ...
    2, 1, 2, 1];
CurrentBlock.Event= [0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, ...
    1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, ...
    0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, ...
    0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, ...
    1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, ...
    0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, ...
    0, 1, 1];
CurrentBlock.Time= [2680, 3380, 10060, 10893, 12942, ...
    12992, 13359, 13409, 14175, 15592, 15858, 15974, ...
    16091, 16258, 17124, 17190, 18207, 18357, 19373, ...
    19873, 23622, 24388, 25005, 25055, 26471, 26537, ...
    27254, 27370, 28370, 29486, 29836, 29869, 30602, ...
    30636, 31086, 31802, 31868, 31885, 32601, 33052, ...
    33068, 33534, 33552, 33568, 34867, 36233, 37833, ...
    38033, 38899, 38916, 41731, 42798, 46713, 47629, ...
    57159, 57975, 60124, 60758, 72387, 73669, 75885, ...
    76185, 76618, 76668, 78517, 79233, 80283, 80433, ...
    81333, 81349, 89130, 90446, 91546, 91579, 92895, ...
    92929, 97177, 97327, 97860, 97927, 101692, 102009, ...
    102158, 102608, 105324, 106523, 107323, 107356, ...
    108873, 110188, 111788, 112904, 114221, 114437, ...
    115804, 115920, 117753, 117836, 119735, 119818];
Block{length(Block)+1}= CurrentBlock;

